sudo: required

services:
  - docker

before_install:
  - docker pull python:2-alpine3.6
  - docker pull python:3-alpine3.6

script:
  - docker build -t python2:latest ./python2/
  - docker build -t python3:latest ./python3/
